name: Generate Metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Profile Details
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/profile.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4ndrxxs
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Seoul
          config_display: large

      # Languages
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4ndrxxs
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_categories: programming
          plugin_languages_limit: 8
          plugin_languages_colors: "0:00D4FF, 1:A855F7, 2:FF3CAC, 3:F7DF1E, 4:3178C6, 5:E34F26, 6:0175C2, 7:02569B"
          config_timezone: Asia/Seoul

      # Habits
      - name: Coding habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4ndrxxs
          base: ""
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_from: 200
          config_timezone: Asia/Seoul
